### ISSUE TITLE
Creating a "User" type in Types.hs fails 

### ISSUE THREAD

**Issue by dabcoder** [iand675/datadog#15]
Hello! I was trying to add a User type to `Types.hs` (as described in https://docs.datadoghq.com/api/#users) with something along these lines:

https://github.com/dabcoder/datadog/blob/edd79aff10e2ef7360fbd64e19bfcb6c3c743281/src/Network/Datadog/Types.hs#L283-L304

This fails because `User` is already used in the `SourceType` here: https://github.com/iand675/datadog/blob/master/src/Network/Datadog/Types.hs#L156. 

Thoughts on this? Am I doing this the right way in the first place?

**Comment by iand675** [comment]
Hi there,

It looks like you're on the right track. For backwards compatibility reasons, we can't necessarily rename the `User` constructor in the `SourceType` enum, though. Looking at the full API, the set of options a new user call takes is not the same as what it returns after creation, so I'd split the two up like so:

``` haskell

data NewUser = NewUser 
  { newUserHandle :: UserHandle
  , newUserName   :: Maybe Text
  , newUserAccessRole :: Maybe UserAccessRole
  } deriving (Eq)

-- smart constructor since name & access_role optional in the API
newUser :: UserHandle -> NewUser
newUser email = NewUser email Nothing Nothing

data User = DatadogUser -- Called it datadog user so it wouldn't overlap with SourceType constructor
  { userVerified :: Bool
  , userName :: Maybe Text
  , userAccessRole :: UserAccessRole
  , ... fill in the rest here
  } deriving (Show, Eq)
```

Hope that helps.

**Comment by dabcoder** [comment]
Thanks for the prompt response! I've done that, so will close this issue and let you know how it goes.

**Comment by dabcoder** [comment]
I'm struggling with that part:

https://github.com/dabcoder/datadog/blob/master/src/Network/Datadog/Internal.hs#L367-L374

Unsure how to deal with the `handle` and `UserAccessRole`. Would anyone have time to look into it? Thanks in advance. 

EDIT: I realised this is rather vague. Basically what's failing is the `newuser ^. handle'` which I'm not using properly here I think as well the `newuser ^. details`. Should there be a `UserSpec` like `EventSpec` or `MonitorSpec`?

**Comment by iand675** [comment]
Well, I think there's a few things going on from what I can see:

1. `handle'` ought to be `handle`, although due to importing `Control.Exception`, which has a conflicting name, you need to fully qualify it:
```haskell
toJSON newuser = Object $ HM.insert "handle" (toJSON (newuser ^. Network.Datadog.Lens.handle)) basemap
```
2. There's no `newUserDetails` field in `NewUser`, so no lens is created called `details`. What is the goal there?
3. The `FromJSON` instance isn't parsing out all of the fields necessary to construct it, so there's a type error going occurring. You'll need to make sure to handle each field, e.g. `DatadogUser <$> v .: "handle" <*> v .: "email" <*> v .: "access_role" .......`

**Comment by iand675** [comment]
Update: I went ahead and got it compiling since I was looking at it anyways. Feel free to use my changes to push things along: https://github.com/iand675/datadog/tree/user-fixups

**Comment by dabcoder** [comment]
Thanks @iand675, much appreciated. I'll carry on with the tests and aim to submit a PR asap.
