### ISSUE TITLE
Update Hackage with newest release

### ISSUE THREAD

**Issue by goakley** [iand675/datadog#3]
Now that this package has a more complete API, the datadog package on Hackage should be updated to the current version (0.2.0.0).

This can be done by anyone in the maintainer group for the package on Hackage.

**Comment by dfithian** [comment]
Now that it's 2 years later (exactly), it'd be nice if this could happen for the current version. We at TVision Insights are using the most current version of this code in a bunch of different repositories and have to add a custom stanza to stack.yaml each time we want to use the library. It would be much easier if it were in Hackage and Stackage. I'm happy to do it, I just need the permissions.

**Comment by TravisWhitaker** [comment]
@iand675 What do you see as the current requirements for a Hackage release?

**Comment by iand675** [comment]
@TravisWhitaker thanks for bringing this to my attention.

@dfithian I would be happy to add you as a maintainer to this project. I don't currently have the bandwidth to manage it, but would love to keep it alive.

**Comment by iand675** [comment]
However, I need your Hackage username.

**Comment by dfithian** [comment]
@iand675 My hackage username is `dfithian`

**Comment by dfithian** [comment]
@iand675 can you also make me a maintainer of this repo on GitHub so that I can add a travis build?

**Comment by iand675** [comment]
@dfithian added you to both

**Comment by dfithian** [comment]
Thank you!

**Comment by dfithian** [comment]
Ah actually @iand675 I can do everything but flip the switch for the Travis build - can you? ([Reference](https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator))

**Comment by iand675** [comment]
Sure, it's on now.

**Comment by dfithian** [comment]
I released this and uploaded the documentation. It's [here](http://hackage.haskell.org/package/datadog-0.2.0.0). Please let me know if you see any issues. I'll close this ticket for now.

**Comment by iand675** [comment]
Great, thanks for taking this on!  





On Thu, Dec 21, 2017 12:40 AM, Dan Fithian notifications@github.com  wrote:
Closed #3.
